### ISSUE TITLE
Large loading time opening entire tree in major 21e

### ISSUE THREAD

**Issue by georgiashay** [npfoss/courseroad2#124] opened 2019-04-03 00:27 UTC
When I open major 21e, then open its sublist Restricted Electives, all of the children are completely open instead of closed.  It's a big tree, so this causes a huge lag, and also the children should be closed by default.

**Comment by ttpcodes** [comment] 2019-04-12 06:49
I had to go back a number of commits to find the regression. Apparently, changing the `index-key` attribute on `v-treeview` from `title` to `index` all those commits back was the cause of it. My guess is that the child elements in the tree all have a title associated with them but do not have an index associated with them, thus causing issues with how `v-treeview` renders things in the next level of child elements. I haven't confirmed this yet though. I'll verify this when I get the chance.

**Comment by georgiashay** [comment] 2019-04-12 16:36
I think this could potentially be solved by using the new "list-id" on the progress-overrides branch.  Every req should have one, and to make it unique we could add the index in front of it.

**Comment by georgiashay** [comment] 2019-04-12 16:47
Ok, I have confirmed that this works and have a working fix on my local progress overrides branch.  I'll push to the PR since it's at least semi-related.

**Comment by ttpcodes** [comment] 2019-04-12 17:18
Cool, I'll reassign the issue to you then since it seems to be part of the `progress-overrides` work.

**Comment by georgiashay** [comment] 2019-04-12 17:19
Thanks for the detective work!

**Comment by ttpcodes** [comment] 2019-04-13 19:34
Fixed by #136.

**Closed by ttpcodes** 2019-04-13 19:34 UTC
